### ISSUE TITLE
_grid_labels_out data type

### ISSUE THREAD

**Issue by t-young31** [UCL/TDMS#67]
The {x_grid_labels_out, y_grid_labels_out, z_grid_labels_out} don't seem to have a consistent datatype 

https://github.com/UCL/TDMS/blob/af3fa4cba628607cfa8d6b65e34e8fd574c601cf/tdms/src/iterator.cpp#L2317

https://github.com/UCL/TDMS/blob/af3fa4cba628607cfa8d6b65e34e8fd574c601cf/tdms/src/iterator.cpp#L2348

I wonder if this is correct? cc: @prmunro

**Comment by willGraham01** [comment]
This will be closed with #215. The `mxComplex` assignment only happens when we don't need to write out the `grid_labels` objects, and so creates empty arrays with no data. The other assignment occurs when we actually have data to write. The new output handler makes this consistent by writing an empty array of `mxDoubles` in the former case.

**Comment by prmunro** [comment]
I'm a bit confused about why the grid labels have been declared to by type mxCOMPLEX, why not leave them as mxREAL? Perhaps I'm missing the point that @willGraham01 is making.

**Comment by willGraham01** [comment]
> I'm a bit confused about why the grid labels have been declared to by type mxCOMPLEX, why not leave them as mxREAL?

I'm not sure why either - #215 does exactly what you say and makes them `mxREAL` in both cases.

At the time of writing the original issue, there's an `if` statement right at the end of the main loop that goes along these lines:
```c++
mxArray *grid_labels; 
if (want_to_write_to_gridlabels) {
  // create mxREAL MATLAB array for gridlabels
  grid_labels = mxCreateNumericArray(non_empty_dims, ..., ..., mxREAL);
  // write some data
}
else {
  // declare an empty mxCOMPLEX MATLAB array for the gridlabels, but don't do anything else with it
  grid_labels = mxCreateNumericArray(empty_dims, ..., ..., mxCOMPLEX);
}
```
Our practice with the outputs that aren't requested by the user is to declare them as empty arrays, so that nothing is written out when it comes to producing the output file. This results in similar `if` statements to the above appearing for some of the other output variables. 

I would guess that the code snippet above was the result of copying the similar conditional statements, and just forgetting to change the `else` clause. Since `grid_labels` is the only variable that is both always real _and_ might not be written to the outputs, the original code may just have forgotten to change the declaration of an empty complex array to an empty real array. `MATLAB` seems to view the "empty array of complex numbers" as being the same as the "empty array of real numbers", so the inconsistency has not caused any issues because the only way `grid_labels` can be complex is if we plan to do nothing with it!

**Comment by prmunro** [comment]
I think you're right @willGraham01. That code is different to what I have in the original version, so it must have been added. It's likely just a paste and copy error (as you suggest). I recommend just changing the occurrence of mxCOMPLEX to mxREAL.
