### ISSUE TITLE
Can't build the unit tests executable on linux

### ISSUE THREAD

**Issue by samcunliffe** [UCL/TDMS#91]
@prmunro very sensibly followed the instructions and:

* the `build` dir didn't get populated (why?)
* `cmake .. -DCMAKE_BUILT_TYPE=Test` didn't create the `tdms_test` file (nor did `ctest` work).

Very embarrassing. We should double-check the instructions vs. GitHub actions are doing the same thing.

**Comment by samcunliffe** [comment]
Hey @willGraham01 

For the second bullet, I think we just gave bad instructions. 

To build the `tdms_tests` executable / `ctest`...
```
cd build; cmake .. -DBUILD_TESTING=ON
ctest # or ./tdms_tests
```

And to build with +debug output
```
cd build; cmake .. --DCMAKE_BUILT_TYPE=Debug
```
`CMAKE_BUILT_TYPE=Test` doesn't do anything.


-------------


I can't be sure, but I have a [hypothesis for the first problem](https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#i-run-an-out-of-source-build-but-cmake-generates-in-source-anyway-why).

I can break CMake by having a rogue CMakeCache.txt one directory up from the build dir (this happens if one ran `cmake` from the wrong directory previously).
```
[ccaecun@login13:build]$ pwd
/lustre/home/ccaecun/TDMS/tdms/build
[ccaecun@login13:build]$ ls ../CMake*.txt
../CMakeCache.txt  ../CMakeLists.txt
[ccaecun@login13:build]$ cmake ..
-- Build spdlog: 1.10.0
-- Build type: Debug
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ccaecun/TDMS/tdms
[ccaecun@login13:build]$ ls
[ccaecun@login13:build]$ make install
make: *** No rule to make target `install'.  Stop.
[ccaecun@login13:build]$ 
```
If the option exists, `cmake .. --fresh <other options>` will fix this problem. I have `--fresh` on my Mac's CMake (3.24.1) but not on Myriad (3.21.1).


Do we need to add anything to any documentation anywhere? My feeling: not. I claim it's just that: we need to be careful when giving CMake instructions.

**Comment by willGraham01** [comment]
> I can break CMake by having a rogue CMakeCache.txt one directory up from the build dir (this happens if one ran cmake from the wrong directory previously).

> Do we need to add anything to any documentation anywhere? My feeling: not. I claim it's just that: we need to be careful when giving CMake instructions.

I agree with both of these, we can always add a reminder to the install instructions.

I will add that it's worth us updating the `readme` at the repo's top-level to include the possible flags you can pass to `cmake`, and a short description of what they do. Suggestion for such changes here:

===README.md

TDMS requires building against [FFTW](https://www.fftw.org/) and [MATLAB](https://www.mathworks.com/products/matlab.html), thus both need to be downloaded and installed prior to compiling TDMS. Install with
```bash
cd tdms
mkdir build; cd build
cmake .. \
# -DMatlab_ROOT_DIR=/usr/local/MATLAB/R2019b/ \
# -DFFTW_ROOT=/usr/local/fftw3/ \
# -DCMAKE_INSTALL_PREFIX=$HOME/.local/
# -DBUILD_TESTING=ON
make install
```
where lines need to be commented in and the paths modified if cmake cannot (1) find MATLAB, (2) find FFTW or (3) install to the default install prefix.

The call to `cmake` may be passed the additional flags listed below, which will alter the behaviour of the build output in the following ways:
- `BUILD_TESTING_ON`: _a helpful description of (or redirection to the instructions for running) the tests_
- `CMAKE_BUILD_TYPE`: _the possible options_, and _a brief description of each_. 

===

I'm also going to add @samcunliffe's comment just before lunch today too:
It might be worth adding helpful "this option does nothing" message(s) to the build. EG if the user tries to pass an option like
```bash
cmake .. -DCMAKE_BUILD_TYPE=Test
```
rather than having this flag silently do nothing (which is the current behaviour), we provide a helpful "did you mean" message like
```
CMAKE_BUILD_TYPE=Test is not a recognised build type, did you mean to pass BUILD_TESTING_ON ?
```
Likewise, we can also consider whether we want the debug build to automatically turn test-building on.
